"""Export numbers and tables from the notebook to the LaTeX paper, so that no number is typed by hand.

    numbers = Numbers()
    numbers.add("statickd.test.macro", 0.5447, digits=3)  # -> \\val{statickd.test.macro} = 0,545
    numbers.write()                                    # jurnal_latex/generated/numbers.tex
    write_table("main", body_lines)                    # jurnal_latex/generated/tab_main.tex

In main.tex:  \\input{generated/numbers}, and inside a tabular  \\rows{generated/tab_main}  (primitive input,
see the preamble of main.tex). An unknown key prints a red
"??" so that a missing number is visible in the PDF. Numbers use Indonesian notation (0,761; 12.744).
"""
from __future__ import annotations

import json
import math
from pathlib import Path

from statickd.config import FINAL_DIR, ROOT

LATEX_DIR = ROOT / "jurnal_latex"
GENERATED_DIR = LATEX_DIR / "generated"


def fmt(x, digits: int = 3, sign: bool = False, percent: bool = False) -> str:
    """Indonesian number format: decimal comma, dot as thousands separator."""
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "--"
    if percent:
        x = 100 * x
    if isinstance(x, int) or (digits == 0):
        s = f"{int(round(x)):,}".replace(",", ".")
    else:
        s = f"{abs(x):,.{digits}f}".replace(",", "_").replace(".", ",").replace("_", ".")
        s = ("-" if x < 0 else "") + s
    if sign and x > 0:
        s = "+" + s
    if s.startswith("-"):
        s = "$-$" + s[1:]
    return s + ("\\%" if percent else "")


def fmt_p(p: float) -> str:
    return "$<$0,001" if p < 0.001 else fmt(p, 3)


class Numbers:
    """Key -> formatted string, written as LaTeX macros and as JSON (for checking)."""

    def __init__(self):
        self.values: dict[str, str] = {}
        self.raw: dict[str, float | str] = {}

    def add(self, key: str, value, digits: int = 3, **kwargs) -> None:
        text = value if isinstance(value, str) else fmt(value, digits, **kwargs)
        self.values[key], self.raw[key] = text, value if isinstance(value, (int, float, str)) else str(value)

    def write(self, path: Path | None = None) -> Path:
        path = Path(path or GENERATED_DIR / "numbers.tex")
        path.parent.mkdir(parents=True, exist_ok=True)
        lines = ["% Generated by notebooks/StaticKD_IPTC_final.ipynb -- do not edit by hand.",
                 "\\makeatletter",
                 "\\providecommand{\\val}[1]{\\ifcsname val@#1\\endcsname\\csname val@#1\\endcsname"
                 "\\else{\\color{red}??}\\fi}"]
        lines += [f"\\expandafter\\def\\csname val@{k}\\endcsname{{{v}}}" for k, v in sorted(self.values.items())]
        lines.append("\\makeatother")
        path.write_text("\n".join(lines) + "\n", encoding="utf8")
        FINAL_DIR.mkdir(parents=True, exist_ok=True)
        (FINAL_DIR / "paper_numbers.json").write_text(json.dumps(self.raw, indent=1, ensure_ascii=False,
                                                                 default=str), encoding="utf8")
        return path


def write_table(name: str, lines: list[str]) -> Path:
    """Write the body of a LaTeX table (rows between \\midrule and \\bottomrule) to generated/tab_<name>.tex."""
    path = GENERATED_DIR / f"tab_{name}.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("% Generated by the notebook -- do not edit by hand.\n" + "\n".join(lines) + "\n", encoding="utf8")
    return path


def eng(text: str) -> str:
    """English technical term in italics, as in the paper (\\eng{...})."""
    return f"\\eng{{{text}}}"
